version: '3.3'
services:
  neo4j:
    image: neo4j:3.5.11-enterprise
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - ./data:/data
    environment:
      - REACT_APP_NEO4J_HOST=bolt://neo4j
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_directories_import=/data
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
